services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin123"
      MYSQL_PASSWORD: docker_pwd
      MYSQL_USER: docker_usr
      MYSQL_DATABASE: docker_db